version: '3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: mdillon/postgis:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

  api:
    build:
      context: .
      dockerfile: ./deploy/django/Dockerfile
    command: /start.sh
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: on-failure
    env_file: .env