# Generated by Django 2.2.7 on 2019-11-08 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alpha_2_code', models.CharField(max_length=2)),
                ('alpha_3_code', models.CharField(max_length=3)),
                ('calling_code', models.CharField(blank=True, max_length=4, null=True)),
                ('capital_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
