# Generated by Django 2.2.7 on 2019-11-08 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20191108_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='continents.Continent'),
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
    ]
