# Generated by Django 2.2.7 on 2019-11-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
